name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - args: [--no-frozen-lockfile]
      
      - name: 构建
        run: |
          pnpm build:cli
          mkdir -p ${{ runner.temp }}/temp/dist
          cp -r dist/* ${{ runner.temp }}/temp/dist/
          cp -r package.json env ${{ runner.temp }}/temp/

      - name: 获取主分支的最新提交消息
        id: commit-message
        run: |
          echo "commit_msg=$(git log origin/${{ github.ref_name }} -1 --pretty=format:'%s')" >> $GITHUB_ENV

      - name: 构建文件
        run: |
          mv .git ${{ runner.temp }}/temp/.git
          cd ${{ runner.temp }}/temp/
          pnpm pkg delete devDependencies

      - name: 提交并推送更改
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "${{ env.commit_msg }}"
          empty: true
          amend: true
          force: true
          branch: "build"
          directory: ${{ runner.temp }}/temp/